### ISSUE TITLE
[CHORE] 홈화면 캘린더 디자인 수정

### ISSUE THREAD

**Issue by yunkyung-Hwang** [hojoon7807/hehwa-ios#18]
## Issue
- 홈화면 디자인 수정
- 캘린더 디자인 수정

## Todo

- [x] calendar design
- [x] calendar color(week, selected date, today)
- [ ] 주간 이동 시 일요일이 선택된 날
- [x] 키보드 inset 수정
