### ISSUE TITLE
[FEAT] 홈화면 서버 통신

### ISSUE THREAD

**Issue by yunkyung-Hwang** [hojoon7807/hehwa-ios#41]
## Issue
홈화면 서버 통신

## Todo
- [x] 캘린더 숙제 있는 날 연결
- [x] 숙제 안한 날 표시
- [ ] 일자별 숙제 목록 연결
